services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: iijiatoh1/test:latest
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: development

  caddy:
    image: caddy:2.6.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app