ci: test-db-prepare
	docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app

test-db-prepare:
	docker-compose exec db psql -U postgres -c "CREATE DATABASE IF NOT EXISTS postgres;"

compose-setup:
	docker-compose run --rm app make setup

compose-test:
	docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app

compose-dev:
	docker-compose up

test: ci

compose-down:
	docker-compose down

compose-production-build:
	docker-compose -f docker-compose.yml build app

compose-production-push:
	docker-compose -f docker-compose.yml push app

production-run:
	docker run -p 8080:8080 -e NODE_ENV=development iijiatoh1/test:latest make dev