name: CI Pipeline

on:
  push:
    branches:
      - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     defaults:
#             run:
#               working-directory: ./devops-for-programmers-project-74

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_TOKEN }}

#       - name: Run tests
#         run: make compose-test

#       - name: Build production image
#         run: docker-compose -f docker-compose.yml build app

#       - name: Push image to Docker Hub
#         run: docker-compose -f docker-compose.yml push app

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify project structure
        run: |
          pwd
          ls -la
          echo "Makefile exists: $(test -f Makefile && echo 'YES' || echo 'NO')"

      - name: Set up project
        run: |
          ls -la  # для отладки - проверяем содержимое
          cat MAKEFILE  # проверяем что Makefile существует

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app

      - name: Build and push
        run: |
          docker-compose -f docker-compose.yml build app
          docker-compose -f docker-compose.yml push app